# Generated by Django 5.0.3 on 2024-03-04 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('prod_cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField()),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.IntegerField()),
                ('prod_brand', models.CharField(max_length=100)),
                ('prod_cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
